[package]
org = "ldclakmal"
name = "oauth1"
version = "1.0.4"
authors = ["Chanaka Lakmal"]
repository = "https://github.com/ldclakmal/ballerina-oauth1.0a"
license = ["Apache-2.0"]
keywords = ["ballerina", "oauth", "oauth1.0", "oauth1.0a", "authorization"]
